### ISSUE TITLE
Support discriminator as function in byValues()

### ISSUE THREAD

**Issue by flumenh** [cosimochellini/sort-es#8]
in `byValue` we are able to specify a simple key, or a function that returns the actual value, as discriminator. This allows us to not only sort by first level attributes, but by any deep property in the object.

We loose that options in `byValues()` where `SortableTuple` only accepts `Tkey` as first parameter. Looking at the code 

https://github.com/cosimochellini/sort-es/blob/7a9495520e170a5dfbfa2530f24d63e7210b000c/src/sortables/byValues.ts#L23-L33

i see no reason not to support that. I'm wrong?

Thanks for this little library. Saves us a looot of work.

**Comment by cosimochellini** [comment]
hey @flumenh you're correct! , I didn't implement this feature simply because I never needed it 😄.
I'll implement this feature in the coming days/weeks, otherwise, a PR is welcome 😊

**Comment by cosimochellini** [comment]
@flumenh hey, in the new version `1.6.0`+  I've added the possibility to sort using a "lambda"!, now you can do something like this!

```typescript
const arraySorted = currentUnsorted.sort(
      byValues([
        [(x) => x.prop, byString()],
        [(x) => x.your.nested?.funciton() ?? 0, byNumber()],
      ])
    );
``` 

The only drawback is that now this could be the only possible way to use the byValues function, 
this is caused by a very complex type of inference that gives some problems with the old `keyof T` type.

I thought a lot about this tradeoff but I feel that this solution is 
1) more flexible
2) easier to understand for the novice users

If you have any problems or doubts, please do not hesitate to contact me!
